# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ParseStarterProject-Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 	pod 'Stripe'
	pod 'LMGeocoder'
	pod 'ParseUI'
	pod 'Parse'

end
